<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-30T00:23:06Z" name="Suite" finished-at="2024-12-30T00:24:21Z" duration-ms="75278">
    <groups>
      <group name="negativeCases">
        <method signature="NegativeScenarios.loginFail()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" name="loginFail" class="com.automation.SeleniumFramework.Test.NegativeScenarios"/>
      </group> <!-- negativeCases -->
      <group name="purchase">
        <method signature="StandaloneTest.submitOrder(java.util.HashMap)[pri:0, instance:com.automation.SeleniumFramework.Test.StandaloneTest@386f0da3]" name="submitOrder" class="com.automation.SeleniumFramework.Test.StandaloneTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-12-30T00:23:06Z" name="PositiveScenario" finished-at="2024-12-30T00:23:48Z" duration-ms="42759">
      <class name="com.automation.SeleniumFramework.Test.StandaloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.automation.SeleniumFramework.Test.StandaloneTest@386f0da3]" started-at="2024-12-30T00:23:06Z" name="launchApplication" finished-at="2024-12-30T00:23:25Z" duration-ms="19014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.automation.SeleniumFramework.Test.StandaloneTest@386f0da3]" started-at="2024-12-30T00:23:25Z" name="submitOrder" data-provider="getData" finished-at="2024-12-30T00:23:43Z" duration-ms="18252" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Rizor123, email=rizor365@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.automation.SeleniumFramework.Test.StandaloneTest@386f0da3]" started-at="2024-12-30T00:23:43Z" name="tearDown" finished-at="2024-12-30T00:23:43Z" duration-ms="70" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.automation.SeleniumFramework.Test.StandaloneTest@386f0da3]" started-at="2024-12-30T00:23:43Z" name="launchApplication" finished-at="2024-12-30T00:23:47Z" duration-ms="4445" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistory()[pri:0, instance:com.automation.SeleniumFramework.Test.StandaloneTest@386f0da3]" started-at="2024-12-30T00:23:47Z" name="orderHistory" finished-at="2024-12-30T00:23:48Z" depends-on-methods="com.automation.SeleniumFramework.Test.StandaloneTest.submitOrder" duration-ms="794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistory -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.automation.SeleniumFramework.Test.StandaloneTest@386f0da3]" started-at="2024-12-30T00:23:48Z" name="tearDown" finished-at="2024-12-30T00:23:48Z" duration-ms="120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.automation.SeleniumFramework.Test.StandaloneTest -->
    </test> <!-- PositiveScenario -->
    <test started-at="2024-12-30T00:23:49Z" name="NegativeScenario" finished-at="2024-12-30T00:24:21Z" duration-ms="32215">
      <class name="com.automation.SeleniumFramework.Test.NegativeScenarios">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:23:49Z" name="launchApplication" finished-at="2024-12-30T00:23:53Z" duration-ms="4582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginFail()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:23:53Z" name="loginFail" finished-at="2024-12-30T00:23:54Z" duration-ms="475" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or passwor.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or passwor.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.automation.SeleniumFramework.Test.NegativeScenarios.loginFail(NegativeScenarios.java:40)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:23:54Z" name="tearDown" finished-at="2024-12-30T00:23:54Z" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:23:54Z" name="launchApplication" finished-at="2024-12-30T00:23:59Z" duration-ms="4714" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginFail()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:23:59Z" name="loginFail" finished-at="2024-12-30T00:24:00Z" duration-ms="1065" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or passwor.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or passwor.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.automation.SeleniumFramework.Test.NegativeScenarios.loginFail(NegativeScenarios.java:40)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:24:00Z" name="tearDown" finished-at="2024-12-30T00:24:00Z" duration-ms="108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:24:00Z" name="launchApplication" finished-at="2024-12-30T00:24:05Z" duration-ms="4460" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="validateProductNameIncart()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:24:05Z" name="validateProductNameIncart" finished-at="2024-12-30T00:24:21Z" duration-ms="16217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateProductNameIncart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.automation.SeleniumFramework.Test.NegativeScenarios@62ef27a8]" started-at="2024-12-30T00:24:21Z" name="tearDown" finished-at="2024-12-30T00:24:21Z" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.automation.SeleniumFramework.Test.NegativeScenarios -->
    </test> <!-- NegativeScenario -->
  </suite> <!-- Suite -->
</testng-results>
